services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vacation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: meggie87/stats-backend:v4
    ports:
      - "9000:9000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vacation_db
      DB_USER: postgres
      DB_PASSWORD: 123456
    restart: always

  frontend:
    image: meggie87/stats-frontend:v5
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  vacations:
    image: meggie87/vacations:v3
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vacation_db
      DB_USER: postgres
      DB_PASSWORD: 123456
    restart: always

volumes:
  pg_data:
